;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-word-dwim
        paredit-backward
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-splice-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        eval-buffer
        smex
        ))
