(setq frame-title-format '(buffer-file-name "%f" ("%b")))
(dolist (feature '(menu tool scroll))
  (funcall (intern (format "%s-bar-mode" feature)) -1))

(load (setq custom-file "~/.custom.el") 'noerror)

(if (string-match "mingw" system-configuration)
    (set-face-attribute 'default nil :height 115 :family "Consolas")
  ;; (set-face-attribute 'default nil :height 105 :family "Source Code Pro")
  (set-face-attribute 'default nil :height 105 :family "Fira Mono")
  ;; (set-face-attribute 'default nil :height 105 :family "Droid Sans Mono")
  )

(add-to-list 'load-path (concat user-emacs-directory "site-lisp"))

(defun safe-require (package)
  (condition-case err (require package)
    ((debug error) (message "%s" (error-message-string err)))))

(mapc #'safe-require '(defuns prefs keys progmodes mmm devenv esk prelude))

(package-initialize)

(if (file-exists-p locals-file) (load locals-file))
(update-autoloads)
(add-to-list 'load-path (expand-file-name ".." autoload-file))

(line-number-mode)
(column-number-mode)
(winner-mode)
(cua-mode)
(electric-pair-mode)
(winring-initialize)
(global-auto-revert-mode)
(show-paren-mode)
(ido-mode)
(ido-ubiquitous)
(global-whitespace-cleanup-mode)
(yas-global-mode)
(savehist-mode)
(global-diff-hl-mode)
(global-undo-tree-mode)
(global-company-mode)
(hes-mode)
(projectile-global-mode)
;;(global-discover-mode)
(highlight-tail-mode)
(global-smartscan-mode)
(sml/setup)
(ace-link-setup-default)
